#!/usr/bin/python3

import app
import config
import logging
from argparse import ArgumentParser
from boto3 import session


def _get_args():
    parser = ArgumentParser()
    required = parser.add_argument_group("required arguments")
    parser.add_argument("-r", "--region", metavar="\b", default="eu-west-1",
                        help="AWS service region. Default is 'eu-west-1'")
    required.add_argument("-e", "--endpoint", metavar="\b", required=True,
                          help="AWS service domain endpoint.")
    return parser.parse_args()


def main():
    logging.basicConfig(level=logging.INFO)
    logging.info("Proxy started")

    args = _get_args()
    config.aws_credentials = session.Session().get_credentials()

    if config.aws_credentials:
        logging.info("Successfully loaded AWS credentials from %s" %
                     config.aws_credentials.method)
    else:
        logging.error("No credential found")
        exit(1)

    config.aws_region = args.region
    config.aws_endpoint = args.endpoint

    app.start()


if __name__ == "__main__":
    main()
